#!/usr/bin/env python3
"""Rebuild recorded cave effects; see audio/recorded/README.md for source/license."""
import array, math, pathlib, sys, wave
root=pathlib.Path(__file__).resolve().parents[1]
with wave.open(str(root/'audio/recorded/rockfall-source.wav'),'rb') as w:
    assert (w.getnchannels(),w.getsampwidth(),w.getframerate())==(2,2,44100)
    raw=array.array('h',w.readframes(w.getnframes()))
if sys.byteorder!='little':raw.byteswap()
source=[(raw[i]+raw[i+1])*.5 for i in range(0,len(raw),2)]
rate=22050
clips=[('RUMBLE','cave-rumble',.95,.65,.48,500,5.0),('CRASH','cave-crash',.46,7.125,.65,1600,3.0)]
arrays=[];methods=[]
for name,file,duration,start,speed,cutoff,boost in clips:
    n=round(duration*rate);values=[];dc=low=body=0
    for i in range(n):
        at=start*44100+i*44100/rate*speed;j=int(at)
        v=source[j]+(source[j+1]-source[j])*(at-j)
        dc+=(1-math.exp(-2*math.pi*28/rate))*(v-dc)
        low+=(1-math.exp(-2*math.pi*cutoff/rate))*(v-dc-low)
        body+=(1-math.exp(-2*math.pi*180/rate))*(low-body)
        u=i/(n-1)
        env=(1-u)**2 if name=='CRASH' else min(1,(1-u)/.40)**2
        values.append((low+boost*body)*min(1,i/(rate*.008))*env)
    gain=.85*32767/max(map(abs,values));pcm=[round(v*gain) for v in values]
    with wave.open(str(root/f'audio/recorded/{file}.wav'),'wb') as w:
        w.setparams((1,2,rate,0,'NONE','none'));data=array.array('h',pcm)
        if sys.byteorder!='little':data.byteswap()
        w.writeframes(data.tobytes())
    h=''.join(f'{v&65535:04x}' for v in pcm)
    arrays.append('    private static final String[] '+name+' = {\n'+''.join('        "'+h[i:i+4000]+'",\n' for i in range(0,len(h),4000))+'    };\n')
    methods.append(f'    static short[] {name.lower()}() {{ return decode({name}, {n}); }}\n')
java='''package com.dddumpling.game;

/** CC0 cliff-rock field recording; generated by tools/prepare-rock-recording.py. */
final class RockRecording {
    static final float RUMBLE_DURATION = .95f, CRASH_DURATION = .46f;
    private RockRecording() {}
'''+''.join(methods)+'''    private static short[] decode(String[] chunks, int length) {
        short[] pcm = new short[length];
        int at = 0;
        for (String chunk : chunks)
            for (int i = 0; i < chunk.length(); i += 4)
                pcm[at++] = (short) Integer.parseInt(chunk.substring(i, i + 4), 16);
        return pcm;
    }
'''+''.join(arrays)+'}\n'
(root/'src/com/dddumpling/game/RockRecording.java').write_text(java)
