#!/usr/bin/env python3
"""Prepare the user-supplied Octopulse wave cue for every audio backend."""
import array
import os
from pathlib import Path
import subprocess
import sys
import wave

root = Path(__file__).resolve().parents[1]
source = root / "audio/recorded/octo-wave-source.m4a"
env = os.environ.copy()
# Codex's Termux launcher may preload an older libc++ than FFmpeg needs.
termux = Path("/data/data/com.termux/files/usr/lib")
if termux.exists():
    env["LD_LIBRARY_PATH"] = str(termux)
raw = subprocess.check_output([
    "ffmpeg", "-v", "error", "-i", str(source), "-map", "0:a:0",
    "-af", "lowpass=f=1000:p=2", "-ac", "1", "-ar", "22050", "-f", "s16le", "-"
], env=env)
samples = array.array("h", raw)
if sys.byteorder != "little":
    samples.byteswap()
rate = 22050
# Preserve both sounds; remove the quiet lead-in and recording tail.
values = list(samples[round(.68 * rate):round(2.66 * rate)])
for i in range(len(values)):
    values[i] *= min(1, i / (.008 * rate), (len(values) - 1 - i) / (.025 * rate))
gain = .85 * 32767 / max(map(abs, values))
pcm = [round(v * gain) for v in values]
out = root / "audio/recorded/octo-wave.wav"
with wave.open(str(out), "wb") as w:
    w.setparams((1, 2, rate, 0, "NONE", "none"))
    encoded = array.array("h", pcm)
    if sys.byteorder != "little":
        encoded.byteswap()
    w.writeframes(encoded.tobytes())
hexed = "".join(f"{v & 65535:04x}" for v in pcm)
chunks = [hexed[i:i+4000] for i in range(0, len(hexed), 4000)]
java = """package com.dddumpling.game;

/** User recording. Generated by tools/prepare-octo-wave.py; see audio/recorded/README.md. */
final class OctoWaveRecording {
    private OctoWaveRecording() {}
    static short[] build() {
        short[] pcm = new short[%d];
        int at = 0;
        for (String chunk : PCM)
            for (int i = 0; i < chunk.length(); i += 4)
                pcm[at++] = (short) Integer.parseInt(chunk.substring(i, i + 4), 16);
        return pcm;
    }
    private static final String[] PCM = {
""" % len(pcm)
java += "".join('        "' + c + '",\n' for c in chunks) + "    };\n}\n"
(root / "src/com/dddumpling/game/OctoWaveRecording.java").write_text(java)
print(f"Octopulse wave: {len(pcm)} samples, {len(pcm)/rate:.2f}s")
