#!/usr/bin/env python3
"""Rebuild the CC0 cart sample; source/license are in audio/recorded/README.md."""
import array, math, pathlib, sys, wave
root=pathlib.Path(__file__).resolve().parents[1]
with wave.open(str(root/'audio/recorded/minecart-source.wav'),'rb') as w:
    assert (w.getnchannels(),w.getsampwidth(),w.getframerate())==(1,2,44100)
    source=array.array('h',w.readframes(w.getnframes()))
if sys.byteorder!='little':source.byteswap()
# Lower playback pitch for weight, then remove rumbling DC and soften abrasive hiss.
rate=22050;n=int(1.2*rate);values=[];low=body=dc=0
for i in range(n):
    at=4.0*44100+i*44100/rate*.78
    j=int(at);v=source[j]+(source[j+1]-source[j])*(at-j)
    dc+=(1-math.exp(-2*math.pi*35/rate))*(v-dc)
    low+=(1-math.exp(-2*math.pi*1100/rate))*(v-dc-low)
    body+=(1-math.exp(-2*math.pi*230/rate))*(low-body)
    values.append((low+body*1.7)*min(1,i/(rate*.012),(n-1-i)/(rate*.025)))
gain=.85*32767/max(map(abs,values));pcm=[round(v*gain) for v in values]
with wave.open(str(root/'audio/recorded/cart-roll.wav'),'wb') as w:
    w.setparams((1,2,rate,0,'NONE','none'));a=array.array('h',pcm)
    if sys.byteorder!='little':a.byteswap()
    w.writeframes(a.tobytes())
hexed=''.join(f'{v&65535:04x}' for v in pcm)
chunks=[hexed[i:i+4000] for i in range(0,len(hexed),4000)]
java='''package com.dddumpling.game;

/** Recorded CC0 rail-style loop. Generated by tools/prepare-cart-recording.py. */
final class CartRecording {
    static final float DURATION = 1.20f;
    private CartRecording() {}
    static short[] build() {
        short[] pcm = new short[26460];
        int at = 0;
        for (String chunk : PCM)
            for (int i = 0; i < chunk.length(); i += 4)
                pcm[at++] = (short) Integer.parseInt(chunk.substring(i, i + 4), 16);
        return pcm;
    }
    private static final String[] PCM = {
'''+''.join('        "'+c+'",\n' for c in chunks)+'    };\n}\n'
(root/'src/com/dddumpling/game/CartRecording.java').write_text(java)
print('cart-roll:',n,'samples,',len(java),'Java bytes')
