#!/usr/bin/env python3
"""Regenerate Ninja's three airy swishes; provenance: audio/recorded/README.md."""
from pathlib import Path
import math, struct, wave

ROOT = Path(__file__).resolve().parents[1]
with wave.open(str(ROOT / 'audio/recorded/ninja-swishes-source.wav'), 'rb') as w:
    assert (w.getnchannels(), w.getsampwidth(), w.getframerate()) == (1, 2, 48000)
    source = [v / 32768 for (v,) in struct.iter_unpack('<h', w.readframes(w.getnframes()))]

# Match the selected 44.1 kHz audition processing before converting to the game's rate.
def excerpt(start, end):
    x = source[int(start * 48000):int(end * 48000)]
    peak = max(map(abs, x))
    onset = next(i for i, v in enumerate(x) if abs(v) > peak * .025)
    x = x[max(0, onset - int(48000 * .003)):]
    rate = 44100
    n = min(int(.18 * rate), int(len(x) * rate / 48000))
    alpha = 1 - math.exp(-2 * math.pi * 2300 / rate)
    highpass = 1 - math.exp(-2 * math.pi * 130 / rate)
    low = low2 = dc = 0.
    values = []
    for i in range(n):
        pos = i * 48000 / rate
        j = int(pos)
        f = pos - j
        v = x[j] * (1 - f) + x[min(j + 1, len(x) - 1)] * f
        low += alpha * (v - low)
        low2 += alpha * (low - low2)
        dc += highpass * (low2 - dc)
        fade = max(0, min(1, i / (.006 * rate), (n - 1 - i) / (.025 * rate)))
        values.append((low2 - dc) * fade)
    gain = min(2., .17 / max(map(abs, values)))
    # The source already rolls off above 2.3 kHz; average adjacent samples for 22.05 kHz.
    pcm = [round((values[i] + values[i + 1]) * .5 * gain * 32767)
           for i in range(0, len(values) - 1, 2)]
    pcm[0] = pcm[-1] = 0
    return pcm

clips = [excerpt(a, b) for a, b in [(0.035, .25), (1.115, 1.35), (1.965, 2.20)]]
for i, pcm in enumerate(clips):
    with wave.open(str(ROOT / f'audio/recorded/ninja-swish-{i+1}.wav'), 'wb') as w:
        w.setparams((1, 2, 22050, 0, 'NONE', 'none'))
        w.writeframes(b''.join(struct.pack('<h', v) for v in pcm))

java = '''package com.dddumpling.game;

/** Cartoon Swishes by Phil Strahl, CC BY 4.0. See assets/AudioCredits.txt.
 * Generated by tools/prepare-ninja-swishes.py; retain the audition's quiet gain. */
final class NinjaSwishRecording {
    static final int COUNT = 3;
    static final float DURATION = .18f;
    private NinjaSwishRecording() {}
    static short[] build(int variant) {
        String[] data = PCM[variant];
        int size = 0;
        for (String chunk : data) size += chunk.length() / 4;
        short[] pcm = new short[size];
        int at = 0;
        for (String chunk : data)
            for (int i = 0; i < chunk.length(); i += 4)
                pcm[at++] = (short) Integer.parseInt(chunk.substring(i, i + 4), 16);
        return pcm;
    }
    private static final String[][] PCM = {
'''
for pcm in clips:
    hexed = ''.join(f'{v & 65535:04x}' for v in pcm)
    java += '        {\n' + ''.join('            "' + hexed[i:i+4000] + '",\n' for i in range(0, len(hexed), 4000)) + '        },\n'
java += '    };\n}\n'
(ROOT / 'src/com/dddumpling/game/NinjaSwishRecording.java').write_text(java)
